# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activation_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'activation_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61\x63tivation_stream.proto\x12\x0c\x64llm.network\"\xc9\x01\n\x11\x41\x63tivationPayload\x12\x13\n\x0bprompt_hash\x18\x01 \x01(\x04\x12\x1a\n\x12task_serial_number\x18\x02 \x01(\r\x12\x13\n\x0blayer_index\x18\x03 \x01(\r\x12\x12\n\nglobal_min\x18\x04 \x01(\x02\x12\x12\n\nglobal_max\x18\x05 \x01(\x02\x12\x14\n\x0cscale_factor\x18\x06 \x01(\x02\x12\x18\n\x10quantized_tensor\x18\x07 \x01(\x0c\x12\x16\n\x0esparse_bitmask\x18\x08 \x01(\x0c\"3\n\tStreamAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2f\n\x10\x41\x63tivationStream\x12R\n\x16StreamLayerActivations\x12\x1f.dllm.network.ActivationPayload\x1a\x17.dllm.network.StreamAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activation_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVATIONPAYLOAD']._serialized_start=42
  _globals['_ACTIVATIONPAYLOAD']._serialized_end=243
  _globals['_STREAMACK']._serialized_start=245
  _globals['_STREAMACK']._serialized_end=296
  _globals['_ACTIVATIONSTREAM']._serialized_start=298
  _globals['_ACTIVATIONSTREAM']._serialized_end=400
# @@protoc_insertion_point(module_scope)
