// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: data-plane/proto/activation_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivationStream_StreamLayerActivations_FullMethodName = "/dllm.network.ActivationStream/StreamLayerActivations"
)

// ActivationStreamClient is the client API for ActivationStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivationStreamClient interface {
	StreamLayerActivations(ctx context.Context, in *ActivationPayload, opts ...grpc.CallOption) (*StreamAck, error)
}

type activationStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationStreamClient(cc grpc.ClientConnInterface) ActivationStreamClient {
	return &activationStreamClient{cc}
}

func (c *activationStreamClient) StreamLayerActivations(ctx context.Context, in *ActivationPayload, opts ...grpc.CallOption) (*StreamAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamAck)
	err := c.cc.Invoke(ctx, ActivationStream_StreamLayerActivations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivationStreamServer is the server API for ActivationStream service.
// All implementations must embed UnimplementedActivationStreamServer
// for forward compatibility.
type ActivationStreamServer interface {
	StreamLayerActivations(context.Context, *ActivationPayload) (*StreamAck, error)
	mustEmbedUnimplementedActivationStreamServer()
}

// UnimplementedActivationStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivationStreamServer struct{}

func (UnimplementedActivationStreamServer) StreamLayerActivations(context.Context, *ActivationPayload) (*StreamAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamLayerActivations not implemented")
}
func (UnimplementedActivationStreamServer) mustEmbedUnimplementedActivationStreamServer() {}
func (UnimplementedActivationStreamServer) testEmbeddedByValue()                          {}

// UnsafeActivationStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivationStreamServer will
// result in compilation errors.
type UnsafeActivationStreamServer interface {
	mustEmbedUnimplementedActivationStreamServer()
}

func RegisterActivationStreamServer(s grpc.ServiceRegistrar, srv ActivationStreamServer) {
	// If the following call panics, it indicates UnimplementedActivationStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivationStream_ServiceDesc, srv)
}

func _ActivationStream_StreamLayerActivations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationStreamServer).StreamLayerActivations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivationStream_StreamLayerActivations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationStreamServer).StreamLayerActivations(ctx, req.(*ActivationPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivationStream_ServiceDesc is the grpc.ServiceDesc for ActivationStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivationStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dllm.network.ActivationStream",
	HandlerType: (*ActivationStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamLayerActivations",
			Handler:    _ActivationStream_StreamLayerActivations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data-plane/proto/activation_stream.proto",
}
