// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: data-plane/proto/activation_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Optimized network payload for the 35% compressed tensor data
type ActivationPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptHash       uint64                 `protobuf:"varint,1,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`                     // Unique conversation identifier (Macro-route mapping)
	TaskSerialNumber uint32                 `protobuf:"varint,2,opt,name=task_serial_number,json=taskSerialNumber,proto3" json:"task_serial_number,omitempty"` // Fixed serial (0-4) mapped to our speculative branches
	LayerIndex       uint32                 `protobuf:"varint,3,opt,name=layer_index,json=layerIndex,proto3" json:"layer_index,omitempty"`                     // The exact downstream layer target (e.g., Layer 8)
	// Low-Level Block-Wise Quantization Parameters
	GlobalMin   float32 `protobuf:"fixed32,4,opt,name=global_min,json=globalMin,proto3" json:"global_min,omitempty"`       // Min value from float32 scan
	GlobalMax   float32 `protobuf:"fixed32,5,opt,name=global_max,json=globalMax,proto3" json:"global_max,omitempty"`       // Max value from float32 scan
	ScaleFactor float32 `protobuf:"fixed32,6,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"` // Dynamic scale multiplier
	// The Compressed Data Fields
	QuantizedTensor []byte `protobuf:"bytes,7,opt,name=quantized_tensor,json=quantizedTensor,proto3" json:"quantized_tensor,omitempty"` // Packed INT8 bytes of our 35% outlier peaks
	SparseBitmask   []byte `protobuf:"bytes,8,opt,name=sparse_bitmask,json=sparseBitmask,proto3" json:"sparse_bitmask,omitempty"`       // Compressed binary mask (8 boolean flags packed per byte)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivationPayload) Reset() {
	*x = ActivationPayload{}
	mi := &file_data_plane_proto_activation_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationPayload) ProtoMessage() {}

func (x *ActivationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_data_plane_proto_activation_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationPayload.ProtoReflect.Descriptor instead.
func (*ActivationPayload) Descriptor() ([]byte, []int) {
	return file_data_plane_proto_activation_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ActivationPayload) GetPromptHash() uint64 {
	if x != nil {
		return x.PromptHash
	}
	return 0
}

func (x *ActivationPayload) GetTaskSerialNumber() uint32 {
	if x != nil {
		return x.TaskSerialNumber
	}
	return 0
}

func (x *ActivationPayload) GetLayerIndex() uint32 {
	if x != nil {
		return x.LayerIndex
	}
	return 0
}

func (x *ActivationPayload) GetGlobalMin() float32 {
	if x != nil {
		return x.GlobalMin
	}
	return 0
}

func (x *ActivationPayload) GetGlobalMax() float32 {
	if x != nil {
		return x.GlobalMax
	}
	return 0
}

func (x *ActivationPayload) GetScaleFactor() float32 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *ActivationPayload) GetQuantizedTensor() []byte {
	if x != nil {
		return x.QuantizedTensor
	}
	return nil
}

func (x *ActivationPayload) GetSparseBitmask() []byte {
	if x != nil {
		return x.SparseBitmask
	}
	return nil
}

type StreamAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	GeneratedToken string                 `protobuf:"bytes,3,opt,name=generated_token,json=generatedToken,proto3" json:"generated_token,omitempty"` // FIX: The network pipeline return lane for text delivery
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_data_plane_proto_activation_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_data_plane_proto_activation_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_data_plane_proto_activation_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StreamAck) GetGeneratedToken() string {
	if x != nil {
		return x.GeneratedToken
	}
	return ""
}

var File_data_plane_proto_activation_stream_proto protoreflect.FileDescriptor

const file_data_plane_proto_activation_stream_proto_rawDesc = "" +
	"\n" +
	"(data-plane/proto/activation_stream.proto\x12\fdllm.network\"\xb6\x02\n" +
	"\x11ActivationPayload\x12\x1f\n" +
	"\vprompt_hash\x18\x01 \x01(\x04R\n" +
	"promptHash\x12,\n" +
	"\x12task_serial_number\x18\x02 \x01(\rR\x10taskSerialNumber\x12\x1f\n" +
	"\vlayer_index\x18\x03 \x01(\rR\n" +
	"layerIndex\x12\x1d\n" +
	"\n" +
	"global_min\x18\x04 \x01(\x02R\tglobalMin\x12\x1d\n" +
	"\n" +
	"global_max\x18\x05 \x01(\x02R\tglobalMax\x12!\n" +
	"\fscale_factor\x18\x06 \x01(\x02R\vscaleFactor\x12)\n" +
	"\x10quantized_tensor\x18\a \x01(\fR\x0fquantizedTensor\x12%\n" +
	"\x0esparse_bitmask\x18\b \x01(\fR\rsparseBitmask\"s\n" +
	"\tStreamAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fgenerated_token\x18\x03 \x01(\tR\x0egeneratedToken2f\n" +
	"\x10ActivationStream\x12R\n" +
	"\x16StreamLayerActivations\x12\x1f.dllm.network.ActivationPayload\x1a\x17.dllm.network.StreamAckB\x1fZ\x1ddllm-cluster/data-plane/protob\x06proto3"

var (
	file_data_plane_proto_activation_stream_proto_rawDescOnce sync.Once
	file_data_plane_proto_activation_stream_proto_rawDescData []byte
)

func file_data_plane_proto_activation_stream_proto_rawDescGZIP() []byte {
	file_data_plane_proto_activation_stream_proto_rawDescOnce.Do(func() {
		file_data_plane_proto_activation_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_plane_proto_activation_stream_proto_rawDesc), len(file_data_plane_proto_activation_stream_proto_rawDesc)))
	})
	return file_data_plane_proto_activation_stream_proto_rawDescData
}

var file_data_plane_proto_activation_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_plane_proto_activation_stream_proto_goTypes = []any{
	(*ActivationPayload)(nil), // 0: dllm.network.ActivationPayload
	(*StreamAck)(nil),         // 1: dllm.network.StreamAck
}
var file_data_plane_proto_activation_stream_proto_depIdxs = []int32{
	0, // 0: dllm.network.ActivationStream.StreamLayerActivations:input_type -> dllm.network.ActivationPayload
	1, // 1: dllm.network.ActivationStream.StreamLayerActivations:output_type -> dllm.network.StreamAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_plane_proto_activation_stream_proto_init() }
func file_data_plane_proto_activation_stream_proto_init() {
	if File_data_plane_proto_activation_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_plane_proto_activation_stream_proto_rawDesc), len(file_data_plane_proto_activation_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_plane_proto_activation_stream_proto_goTypes,
		DependencyIndexes: file_data_plane_proto_activation_stream_proto_depIdxs,
		MessageInfos:      file_data_plane_proto_activation_stream_proto_msgTypes,
	}.Build()
	File_data_plane_proto_activation_stream_proto = out.File
	file_data_plane_proto_activation_stream_proto_goTypes = nil
	file_data_plane_proto_activation_stream_proto_depIdxs = nil
}
